### ISSUE TITLE
output taxonomy full path?

### ISSUE THREAD

**Issue by wfgui** [KennthShang/PhaGCN2.0#12]
Hi
   Thank you for creating the software, could you consider adding taxonomy's full path to the result?
```
contig_name	idx	prediction
NODE_106	0_0	Deejayvirinae
NODE_108	0_1	Salasmaviridae_like
NODE_110	0_2	Casadabanvirus
```

**Comment by yuanwenguang666** [comment]
Dear

I'm sorry, I don't understand your advice. Do you mean to add a specific ICTV  virus sequences PATH which is in association with test sequence?

**Comment by wfgui** [comment]
> Dear
> 
> I'm sorry, I don't understand your advice. Do you mean to add a specific ICTV virus sequences PATH which is in association with test sequence?

That mean format the output at taxonomy, such as converting it to k__; p__; c__; o__; f__; g__; s__.

**Comment by yuanwenguang666** [comment]
Thanks for your advice that I understand your mean. It is better to output a complete classification path from kingdom to family. We will consider adding it to the new update.

**Comment by yuanwenguang666** [comment]
Thanks for your advice. The complete classification path can be output to the classification result in the updated version.
