### ISSUE TITLE
Why diamond in run_Speed_up.py？

### ISSUE THREAD

**Issue by Asa12138** [KennthShang/PhaGCN2.0#13]
Hello,
I found that run_Speed_up.py has to run diamond and blastp every time, but in fact this part is just database preparation, which should be enough once. Why should it be run in run_Speed_up.py every time?
It takes at least dozens of minutes each time, and the obtained database.dmnd and other files will be overwritten next time.

**Comment by Asa12138** [comment]
I also found that the diamond library was built for ALL_protein.fasta in run_KnowledgeGraph.py. If several tasks are run at the same time, there will definitely still be problems.
The principle of running the program without changing the database itself and only generating intermediate files and output files should be followed for optimization. Looking forward to PhaGCN doing better.

**Comment by yuanwenguang666** [comment]
Dear!
Thank you for your valuable suggestion. I'm sorry we didn't notice that before. The corresponding function will be added in the next week's update.
Thank you again for your suggestions about PhaGCN2 , It's useful.
All the best!!!
Wen-Guang

**Comment by yuanwenguang666** [comment]
Thank you for your advice. It has been fixed in the updated version.
