### ISSUE TITLE
How to open ntw file

### ISSUE THREAD

**Issue by chengwbTOT** [KennthShang/PhaGCN2.0#14]
How to open ntw file?

**Comment by yuanwenguang666** [comment]
Dear!

I apologize for the delayed response. Currently, NTW format files can be visualized using **Cytoscape** or **Gephi.** In these NTW files, the first column represents the source in the network graph, while the second column represents the target. We can consider the weight of these connections to be 1. Additionally, any point in the network graph that contains "test" in its name indicates a test point, which corresponds to a predicted sequence. All other points with different names represent a virus from the ICTV database.

All the best！
Wen-Guang

**Comment by chengwbTOT** [comment]
Dear Wen-Guang,
Thank you for your detailed explanation and suggestions! The issue has been resolved. I truly appreciate your help and support.
Best regards
