### ISSUE TITLE
Pre-trained CNN Error for file contig_0

### ISSUE THREAD

**Issue by chengninghui** [KennthShang/PhaGCN2.0#5]
Hi PhaGCNer,
An error showed when i run test.sh : "Pre-trained CNN Error for file contig_0".

my task: 
conda activate phagcn2
export MKL_SERVICE_FORCE_INTEL=1
python run_Speed_up.py --contigs contigs.fa --len 8000

log :
Reported 6420544 pairwise alignments, 6431184 HSPs.
354845 queries aligned.
folder input exist... cleaning dictionary
folder pred exist... cleaning dictionary
folder Split_files exist... cleaning dictionary
folder network exist... cleaning dictionary
Creating Diamond database...
Running Diamond...
Pre-trained CNN Error for file contig_0

File folder
<img width="504" alt="1687260445290" src="https://github.com/KennthShang/PhaGCN2.0/assets/134821847/4f0b8cfd-9112-4650-85e4-17ec43d0c785">

**Comment by zihan-Chen** [comment]
I suppose that you mis-delete the `contig_0` in `pred`. Once, I want to try the `contigs.fa`, I found that I've forgotten to run it in the background, so I stopped the task. To aviod some tmp files which could influence my task, so I delete some directories including `pred` which included nothing. But I failed, I met the same question like yours. So I delete the whole directory of `PhaGCN2.0` and re-unzip it. Then the file `contigs_0` appeared.

**Comment by yuanwenguang666** [comment]
Thank you for your question.
We have checked the test file and did not find any question. The issue may be caused, as Mr Chen.  mentioned, by mistakenly deleting certain folders during the program or installation process. We support you download one again and re-unzip the database. If you still have problems, please do not hesitate to give your valuable comments.

Best,
Wen-Guang
