### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by liaohu1231** [KennthShang/PhaGCN2.0#6]
Running Diamond...
Knowledge Graph Error for file contig_0
Traceback (most recent call last):
  File "/public3/home/sc52870/soft/PhaGCN2.0/run_Speed_up.py", line 129, in <module>
    out = subprocess.check_call(cmd, shell=True)
  File "/public3/home/sc52870/miniconda3/envs/phagcn2/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cat pred/* > phage10_final_prediction.csv' returned non-zero exit status 1.
diamond v0.9.14.115 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

**Comment by liaohu1231** [comment]
Traceback (most recent call last):
  File "run_KnowledgeGraph.py", line 129, in <module>
    _ = subprocess.check_call("cat {0} > {1}".format(file_out_fn+"*", all_protein_f), shell=True)
  File "/public3/home/sc52870/miniconda3/envs/phagcn2/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cat all_proteins/* > out/all_translate_proteins.fa' returned non-zero exit status 1.
Knowledge Graph Error for file contig_0
cat: pred/*: No such file or directory

**Comment by yuanwenguang666** [comment]
Sorry for the slow response.

From your logs, it seems that there are too few matching sequences in your prediction data. I recommend that you test to see if your sequences length is > 1700bp or have no gaps, or use more sequences to test.

Thank you for your question.
WenGuang
