### ISSUE TITLE
create database failed

### ISSUE THREAD

**Issue by mengyuan09876** [KennthShang/PhaGCN2.0#8]
I encountered this problem: 
“Database file: database/ALL_protein.fasta
Opening the database file... No such file or directory
 [0.000229s]
Error: Error calling stat on file database/ALL_protein.fasta
create database failed” 
But when I returned to the database folder, I found that there was a compressed file of ALL_protein. ALL_protein.fasta existed after decompression. But when I run it, I still get this error

**Comment by sugar-sugar1** [comment]
I met this problem too, have you resolve this problem?

**Comment by mengyuan09876** [comment]
I just move my file to the folder where I download PhaGCN2.0

sugar-sugar1 ***@***.***> 于2023年11月27日周一 11:37写道：

**Comment by sugar-sugar1** [comment]
我刚刚也是这样做的，看它好像运行起来了，但是要是站位多的话好麻烦，我尝试把这个软件的路径写到bashrc中，不过好像没有用，不知道是不是我写错了

**Comment by sugar-sugar1** [comment]
我明白了，因为python脚本不能添加到环境变量里去，可以建一个指向 run_Speed_up.py 的符号链接就可以啦

**Comment by yuanwenguang666** [comment]
Thank you for your questions.

The environment path of PhaGCN2 is a relative path. Therefore, you need to enter the working directory of phagcn before using phagcn by `cd PhaGCN2.0`. 

If you have more questions, please do not hesitate answer it in comments.
